config/routes.rb
Rails.application.routes.draw do
  resources :assets

  get 'assets/home'

  root 'assets#index'
  get 'assets/about', to: 'assets#about'

end

app/models/asset.rb
class Asset < ActiveRecord::Base

  belongs_to :user

  before_save { |asset| asset.model = asset.model.titleize }
  before_save { |asset| asset.manufactuer = asset.manufactuer.titleize }
  before_save { |asset| asset.assignee = asset.assignee.titleize }


  validates :asset_tag,
              presence: true,
              uniqueness: true,
              :numericality =>  {:only_integer => true},
              length: {minimum: 8, maximum: 8}
  validates :assignee,
              presence: true,
              length: {minimum: 3, maximum: 50}
  validates :typeofasset,
              presence: true,
              length: {minimum: 3, maximum: 50}
  validates :manufactuer,
              presence: true,
              length: {minimum: 3, maximum: 50}
  validates :location_region,
              presence: true,
              length: {minimum: 3, maximum: 50}
  validates :location_site,
              presence: true,
              length: {minimum: 3, maximum: 50}
  validates :hostname,
              presence: true,
              uniqueness: true,
              length: {minimum: 3, maximum: 50}

  default_scope { order('asset_tag ASC')}
end

app/models/user.rb
class User < ActiveRecord::Base

    has_many :assets

  validates :username,
              presence: true,
              uniqueness: {case_sensitive: false},
              length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email,
              presence: true,
              length: {maximum: 100},
              uniqueness: {case_sensitive: false},
              format: {with: VALID_EMAIL_REGEX}


before_save { self.email = email.downcase }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]

  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @asset = Asset.new
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(asset_params)
    if @asset.save
      flash[:success] = "Asset was successfully created"
      redirect_to asset_path(@asset)
    else
      render 'new'
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    if @asset.update(asset_params)
      flash[:success] = "Article was successfully updated"
      redirect_to asset_path(@asset)
    else
      render 'edit'
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    flash[:success] = "Asset was successfully deleted"
    redirect_to assets_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:asset_tag, :purchasedate, :typeofasset, :manufactuer, :model, :location_region, :location_site, :hostname, :assignee, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<%= render 'shared/errors', obj: @asset %>
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@asset, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :asset_tag %>
          </div>
          <div class="col-sm-2">
            <%= f.text_field :asset_tag, class: "form-control", placeholder: "Asset Number", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :purchasedate %>
          </div>
          <div class="col-sm-2">
            <%= f.text_field :purchasedate, :class => 'datepicker'%>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :Type %>
          </div>
          <div class="col-sm-2">
            <%= f.select :typeofasset, ['Laptop', 'Server', 'Monitor', 'IT Appliance', 'Misc'] %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :Manufactuer %>
          </div>
          <div class="col-sm-3">
            <%= f.text_field :manufactuer, rows: 10, class: "form-control", placeholder: "eg, Dell, Lenovo" %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :Model %>
          </div>
          <div class="col-sm-3">
            <%= f.text_field :model, rows: 10, class: "form-control", placeholder: "Model" %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :Region %>
          </div>
          <div class="col-sm-3">
            <%= f.select :location_region, ['EMEA', 'APAC', 'AMER']%>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :Site %>
          </div>
          <div class="col-sm-3">
            <%= f.select :location_site, ['ADV', 'AMS', 'BUD', 'MAN', 'NBY', 'RNC', 'SNG'] %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :hostname %>
          </div>
          <div class="col-sm-3">
            <%= f.text_field :hostname, rows: 10, class: "form-control", placeholder: "Hostname" %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :assignee %>
          </div>
          <div class="col-sm-3">
            <%= f.text_field :assignee, rows: 10, class: "form-control", placeholder: "Assignee" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg' %>
          </div>
        </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel and return to asset register", assets_path %> ]
    </div>
  </div>
</div>

app/views/assets/edit.html.erb
<h1 align="center">Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/home.html.erb
<h1>Assets#home</h1>
<p>Find me in app/views/assets/home.html.erb</p>

app/views/assets/index.html.erb
<h1 align = "center">Asset Register</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Asset tag</th>
      <th>Purchase Date</th>
      <th>Type</th>
      <th>Manufactuer</th>
      <th>Model</th>
      <th>Location region</th>
      <th>Location site</th>
      <th>Hostname</th>
      <th>Assignee</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.asset_tag %></td>
        <td><%= asset.purchasedate %></td>
        <td><%= asset.typeofasset %></td>
        <td><%= asset.manufactuer %></td>
        <td><%= asset.model %></td>
        <td><%= asset.location_region %></td>
        <td><%= asset.location_site %></td>
        <td><%= asset.hostname %></td>
        <td><%= asset.assignee %></td>
        <td><%= asset.active %></td>
        <td><%= link_to 'Show', asset %></td>
        <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
        <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset', new_asset_path %>

app/views/assets/new.html.erb
<h1 align="center">New asset</h1>

<%= render 'form' %>

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<h2 align="center">Asset: <%= @asset.asset_tag %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center details"><strong>Details:</strong></h4>
  <hr>
  <p>
    <strong>Asset tag:</strong>
    <%= @asset.asset_tag %>
  </p>

  <p>
    <strong>Purchase Date:</strong>
    <%= @asset.purchasedate %>
  </p>

  <p>
    <strong>Manufactuer:</strong>
    <%= @asset.manufactuer %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= @asset.model %>
  </p>

  <p>
    <strong>Location region:</strong>
    <%= @asset.location_region %>
  </p>

  <p>
    <strong>Location site:</strong>
    <%= @asset.location_site %>
  </p>

  <p>
    <strong>Hostname:</strong>
    <%= @asset.hostname %>
  </p>

  <p>
    <strong>Assignee:</strong>
    <%= @asset.assignee %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= @asset.active %>
  </p>
  <div class="asset-actions">
    <%= link_to "Edit this asset", edit_asset_path(@asset), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete this asset", asset_path(@asset), method: :delete,
                data: { confirm: "Are you sure you want to delete the asset?"},
                class: "btn btn-xs btn-danger" %>
    <%= link_to "View all assets", assets_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/layouts/_dropdowns.html.erb
<div class="btn-group pull-right toggleCheck" style="display:none;" id='<%= id %>'>
  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><%= title %><span class="caret"></span></a>
  <ul class="dropdown-menu" style="right: 0; left: auto;">
    <% if type == :search %>
        <li style="padding:5px 10px;"><input class="drop-search focus-open hold" type='text' placeholder='Search' style="margin:0px;"></li>
    <% elsif type == :note %>
        <li style="padding:5px 10px;"><textarea placeholder='Status notes' class="hold focus-open note-box" rows="4" style="margin:0px; resize: none;"></textarea></li>
    <% end %>
    <li style="padding:5px 10px; font-weight:700;"><%= subtitle %></li>
    <div class="choices">
      <% collection.each do |c| %>
          <li><%= link_to (label.(c) + '<span class="comment"></span>').html_safe, '#', :value => value.(c), :path => path, :iden => label.(c).downcase.gsub(/\s/, '-') %></li>
      <% end %>
    </div>
  </ul>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright © <a href="enter in a link here">CloudPay</a>
      Asset Management
    </small>

  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Asset Management", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Assets", assets_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Asset", new_asset_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Admin</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assetmanagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<style type="text/css">
  body { background: #b5bdc3, color: #b5bdc3;  } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>
<div class="container">

  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              prohibited this article from being saved:
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>